"""Independent ML Red-Team Challenge Cases for AI-JobShield (Step 9).

Contains 64 independently authored test cases:
- 32 Legitimate cases (including 16 hard negatives and 10 contrast-pair controls)
- 32 Scam cases (including 16 disguised/indirect scams and 10 contrast-pair controls)

Zero overlap with training_data_v2.csv, benchmark_cases, or adversarial evaluation.
"""
from __future__ import annotations

# Format:
# {
#     "id": int,
#     "name": str,
#     "company": str,
#     "title": str,
#     "text": str,
#     "label": int (0 = legitimate, 1 = scam),
#     "category": str,
#     "contrast_pair_id": str | None,
#     "notes": str
# }

REDTEAM_CASES = [
    # ==================================================================
    # 1. CONTROLLED CONTRAST PAIRS (10 Pairs = 20 Cases)
    # Pairs share sensitive vocabulary (bank, account, payment, crypto,
    # whatsapp, telegram, salary, verification, identity, check), but
    # differ in applicant-directed intent (duty/benefit vs extortion).
    # ==================================================================

    # Pair 1: Payroll bank account credit vs Bank account transfer extortion
    {
        "id": 1,
        "name": "Pair 1 Legit: Direct Deposit Payroll",
        "company": "Kavach Mobility",
        "title": "Fleet Operations Lead",
        "text": "Kavach Mobility is looking for a Fleet Operations Lead in Pune. Responsibilities include supervising daily EV fleet dispatch and driver scheduling. Monthly salary will be deposited directly into your bank account on the last working day of each month. We also provide health cover and gratuity. Submit your CV to recruitment@kavachmobility.in.",
        "label": 0,
        "category": "LEGIT_PAYROLL",
        "contrast_pair_id": "PAIR_01",
        "notes": "Legitimate mention of bank account for salary credit",
    },
    {
        "id": 2,
        "name": "Pair 1 Scam: Bank Account Activation Wire",
        "company": "Kavach Logistics Hub",
        "title": "Fleet Operations Lead",
        "text": "Congratulations, you have been selected as Fleet Operations Lead at Kavach Logistics. To link your corporate payroll profile, transfer 2000 rupees from your bank account to our corporate settlement nodal account to verify account validity before joining date. Send transaction slip to hr-verify@kavachlogistics.com.",
        "label": 1,
        "category": "SCAM_FEE",
        "contrast_pair_id": "PAIR_01",
        "notes": "Scam asking candidate to wire money from bank account",
    },

    # Pair 2: Payment gateway API vs Payment gateway extortion
    {
        "id": 3,
        "name": "Pair 2 Legit: Payment Gateway Architect",
        "company": "VistaraPay Technologies",
        "title": "Staff Backend Engineer",
        "text": "VistaraPay is seeking a Staff Backend Engineer in Bengaluru. You will design resilient payment gateway adapters, manage card tokenization, and optimize bank transfer webhooks for merchant settlements. Qualifications: 7+ years in distributed microservices and PCI-DSS architecture. CTC: 35-45 LPA. Apply at https://vistarapay.io/careers.",
        "label": 0,
        "category": "LEGIT_FINTECH",
        "contrast_pair_id": "PAIR_02",
        "notes": "Technical engineering duties involving payment gateways",
    },
    {
        "id": 4,
        "name": "Pair 2 Scam: Payment Gateway Portal Fee",
        "company": "Vistara Payments Partner",
        "title": "Payment Processing Officer",
        "text": "Immediate appointment for Payment Processing Officer. Work from home. Monthly CTC 45000. Candidates must log into our payment gateway link and complete a 1500 registration charge using UPI to generate their virtual employee token prior to onboarding call.",
        "label": 1,
        "category": "SCAM_FEE",
        "contrast_pair_id": "PAIR_02",
        "notes": "Demands payment via gateway link to register",
    },

    # Pair 3: Blockchain custody protocol vs Crypto wallet funding scam
    {
        "id": 5,
        "name": "Pair 3 Legit: Institutional Crypto Custody Lead",
        "company": "Aether Custody Labs",
        "title": "Senior Blockchain Developer",
        "text": "Aether Custody Labs provides enterprise digital asset custody. We are hiring a Senior Blockchain Developer to audit multi-sig crypto wallet infrastructure, design MPC signing algorithms, and review smart contracts. Requirements: Strong Rust or Go background. Competitive package with token incentives. Apply via careers@aethercustody.com.",
        "label": 0,
        "category": "LEGIT_CRYPTO",
        "contrast_pair_id": "PAIR_03",
        "notes": "Authentic Web3 engineering role",
    },
    {
        "id": 6,
        "name": "Pair 3 Scam: Crypto Wallet Task Deposit",
        "company": "Aether Asset Management",
        "title": "Digital Asset Allocation Assistant",
        "text": "Earn 500 dollars weekly assisting our crypto fund. To initiate daily asset allocation tasks, you must fund your personal candidate crypto wallet with 150 USDT and transfer the gas fee to our smart contract address to unlock payout distribution.",
        "label": 1,
        "category": "SCAM_CRYPTO",
        "contrast_pair_id": "PAIR_03",
        "notes": "Scam instructing applicant to transfer USDT to smart contract",
    },

    # Pair 4: WhatsApp campus logistics vs WhatsApp exclusive interview bypass
    {
        "id": 7,
        "name": "Pair 4 Legit: Campus Coordination via WhatsApp",
        "company": "Thermax Systems",
        "title": "Graduate Engineering Trainee",
        "text": "Thermax Systems is conducting campus hiring for Graduate Engineering Trainees in Pune. All application forms and aptitude links are issued via our official college placement portal. Our HR team has established an auxiliary WhatsApp helpdesk at +91 9423011223 strictly to assist travelling candidates with driving directions to the factory venue.",
        "label": 0,
        "category": "LEGIT_COMM",
        "contrast_pair_id": "PAIR_04",
        "notes": "Official company using WhatsApp strictly for venue directions",
    },
    {
        "id": 8,
        "name": "Pair 4 Scam: WhatsApp Exclusive Offer",
        "company": "Thermax Industrial Staffing",
        "title": "Graduate Engineering Trainee",
        "text": "Direct recruitment at Thermax for Graduate Trainees. No campus interview needed. 100 percent selection. Contact HR Director solely on WhatsApp number +91 8877665544 to receive joining letter. Send resume and 1200 rupees security badge fee immediately.",
        "label": 1,
        "category": "SCAM_FEE",
        "contrast_pair_id": "PAIR_04",
        "notes": "Exclusive WhatsApp channel requesting security fee",
    },

    # Pair 5: Telegram tech community vs Telegram daily task scheme
    {
        "id": 9,
        "name": "Pair 5 Legit: Open Source Telegram Community Evangelist",
        "company": "Hasura Open Source",
        "title": "Developer Advocate",
        "text": "Hasura is looking for a Developer Advocate in Bengaluru. You will create GraphQL tutorials, represent the company at tech conferences, and moderate discussions on our official Telegram developer community and Discord server. Competitive salary and travel allowance. Apply through https://hasura.io/careers.",
        "label": 0,
        "category": "LEGIT_COMM",
        "contrast_pair_id": "PAIR_05",
        "notes": "Legitimate company with developer community on Telegram",
    },
    {
        "id": 10,
        "name": "Pair 5 Scam: Telegram Task Channel",
        "company": "Hasura Media Promotions",
        "title": "Digital Review Partner",
        "text": "Work from phone 1 hour daily. Earn 3000 rupees daily by subscribing to YouTube links and rating mobile apps. Payouts transferred every evening. Join our verified Telegram channel @DailyIncomeHub to start your first task immediately.",
        "label": 1,
        "category": "SCAM_TASK",
        "contrast_pair_id": "PAIR_05",
        "notes": "Telegram task scam promising daily income for likes",
    },

    # Pair 6: Legitimate onboarding background check vs Background check fee extortion
    {
        "id": 11,
        "name": "Pair 6 Legit: Standard Corporate Background Verification",
        "company": "KFin Technologies",
        "title": "Compliance Analyst",
        "text": "KFin Technologies is hiring a Compliance Analyst in Hyderabad. Responsibilities include reviewing mutual fund transactions and statutory filings. As part of post-offer formal onboarding, selected candidates will undergo standard background verification conducted by our third-party audit partner. All costs are fully borne by KFin Technologies. Package: 7-10 LPA.",
        "label": 0,
        "category": "LEGIT_CORP",
        "contrast_pair_id": "PAIR_06",
        "notes": "Company explicitly states employer bears all background check costs",
    },
    {
        "id": 12,
        "name": "Pair 6 Scam: Candidate-Paid Background Verification Fee",
        "company": "KFin Services Recruitment",
        "title": "Compliance Officer",
        "text": "Offer of employment confirmed for Compliance Officer. To process your credential background audit, candidate must remit a third-party proctoring and background screening fee of 2450 INR via UPI to our verification desk within 24 hours to generate clearance certificate.",
        "label": 1,
        "category": "SCAM_FEE",
        "contrast_pair_id": "PAIR_06",
        "notes": "Candidate instructed to remit screening fee via UPI",
    },

    # Pair 7: Corporate equipment provision vs Equipment reimbursement check fraud
    {
        "id": 13,
        "name": "Pair 7 Legit: Employer-Provided Workstation",
        "company": "BrowserStack",
        "title": "Senior Frontend Engineer",
        "text": "BrowserStack is looking for a Senior Frontend Engineer. Remote (India). You will build developer testing interfaces with React and WebGL. We provide a company-owned MacBook Pro, 4K monitor, and annual home office wellness reimbursement directly in your first paycheck. Multi-round technical interview: Live coding and UI design. CTC: 28-36 LPA.",
        "label": 0,
        "category": "LEGIT_REMOTE",
        "contrast_pair_id": "PAIR_07",
        "notes": "Legitimate employer-owned laptop and wellness stipend",
    },
    {
        "id": 14,
        "name": "Pair 7 Scam: Advance Check Hardware Supplier Scam",
        "company": "BrowserStack Solutions Inc",
        "title": "Remote Data Coordinator",
        "text": "Welcome to BrowserStack Solutions! We will courier you an advance corporate cashier check of 3500 dollars. Please deposit the check into your bank account immediately, retain 500 dollars as salary advance, and wire the remaining 3000 dollars to our certified home office hardware supplier for software installation.",
        "label": 1,
        "category": "SCAM_CHECK",
        "contrast_pair_id": "PAIR_07",
        "notes": "Classic fake check equipment reimbursement fraud",
    },

    # Pair 8: Executive senior compensation vs Exorbitant data entry pay
    {
        "id": 15,
        "name": "Pair 8 Legit: Principal Architect 65 LPA",
        "company": "Zepto Technologies",
        "title": "Principal Systems Architect",
        "text": "Zepto is hiring a Principal Systems Architect in Bengaluru to scale our ultra-fast supply chain platform. The ideal candidate has 10+ years architecting event-driven systems handling 100k requests per second in Go and Kafka. Compensation: 60-75 LPA plus ESOPs. Rigorous engineering panel interview process.",
        "label": 0,
        "category": "LEGIT_SENIOR",
        "contrast_pair_id": "PAIR_08",
        "notes": "Senior executive compensation justified by 10+ years experience",
    },
    {
        "id": 16,
        "name": "Pair 8 Scam: Data Entry 5000 Daily",
        "company": "Zepto Express Delivery Hub",
        "title": "Online Form Filling Executive",
        "text": "Earn 5000 rupees daily working from home without any experience! Simple copy paste and captcha entry work on mobile. Daily payment guaranteed. Housewives and students apply now. Send resume to our recruitment WhatsApp to get started today.",
        "label": 1,
        "category": "SCAM_SALARY",
        "contrast_pair_id": "PAIR_08",
        "notes": "Absurdly high daily pay for low-skill data entry",
    },

    # Pair 9: E-commerce Gift card reconciliation vs Gift card fee demand
    {
        "id": 17,
        "name": "Pair 9 Legit: Gift Card Merchant Reconciliation Lead",
        "company": "Nykaa E-Retail",
        "title": "Financial Operations Associate",
        "text": "Nykaa is hiring a Financial Operations Associate in Mumbai. The role involves auditing digital gift card redemptions, reconciling merchant voucher settlement ledgers, and resolving coupon transaction discrepancies with banking partners. Requirements: B.Com/M.Com, 2-4 years accounting experience. CTC: 5.5-7.5 LPA. Apply at careers@nykaa.com.",
        "label": 0,
        "category": "LEGIT_CORP",
        "contrast_pair_id": "PAIR_09",
        "notes": "Auditing retail gift card ledgers",
    },
    {
        "id": 18,
        "name": "Pair 9 Scam: Confirmation Fee in Apple Gift Cards",
        "company": "Nykaa Recruitment Agency",
        "title": "Customer Service Associate",
        "text": "Congratulations, you have cleared all rounds for Customer Service Associate at Nykaa. To activate your corporate workstation license, buy two Apple or Amazon gift cards worth 2500 rupees each and send the scratch codes to our HR desk to complete onboarding setup.",
        "label": 1,
        "category": "SCAM_FEE",
        "contrast_pair_id": "PAIR_09",
        "notes": "Extorting onboarding fee through gift card scratch codes",
    },

    # Pair 10: Official HR joining documents vs Pre-interview Aadhaar/PAN extortion
    {
        "id": 19,
        "name": "Pair 10 Legit: Post-Offer Document Verification",
        "company": "Biocon Biologics",
        "title": "Quality Control Chemist",
        "text": "Biocon is hiring a QC Chemist in Bengaluru. Qualifications: M.Sc in Chemistry with 2 years analytical lab experience. Selection involves a written technical exam and in-person lab assessment. Selected candidates will be required to upload academic certificates and Aadhaar through our secure internal HR portal prior to joining date. Apply at https://www.biocon.com/careers.",
        "label": 0,
        "category": "LEGIT_CORP",
        "contrast_pair_id": "PAIR_10",
        "notes": "Document upload through secure enterprise portal after formal selection",
    },
    {
        "id": 20,
        "name": "Pair 10 Scam: Pre-Interview WhatsApp Document Extortion",
        "company": "Biocon Hiring Desk",
        "title": "Laboratory Assistant",
        "text": "Urgent vacancy for Laboratory Assistant. No written exam. Before scheduling your interview call, candidate must send front and back pictures of original Aadhaar, PAN card, and 3 months bank statement to WhatsApp number +91 9765432109 or application will be rejected.",
        "label": 1,
        "category": "SCAM_DOCS",
        "contrast_pair_id": "PAIR_10",
        "notes": "Demanding sensitive identity documents via WhatsApp prior to interview",
    },

    # ==================================================================
    # 2. ADDITIONAL LEGITIMATE HARD NEGATIVES (12 Cases)
    # Realistic roles with complex, technical, startup, or informal tone.
    # ==================================================================

    {
        "id": 21,
        "name": "Legit Fintech: Core Banking NEFT Settlement Lead",
        "company": "Setu Open Banking",
        "title": "Lead Software Engineer - Core Banking",
        "text": "Setu is hiring a Lead Software Engineer in Bengaluru to build NPCI unified banking connectors. You will own microservices handling high-volume RTGS, NEFT, and IMPS bank transfers, audit banking reconciliation logs, and interface with partner bank clearing systems. Requirements: 6+ years in distributed Java systems. Compensation: 30-42 LPA. Apply at careers@setu.co.",
        "label": 0,
        "category": "LEGIT_FINTECH",
        "contrast_pair_id": None,
        "notes": "Dense banking and transfer terminology in authentic engineering context",
    },
    {
        "id": 22,
        "name": "Legit Crypto: Decentralized Smart Contract Auditor",
        "company": "OpenZeppelin India",
        "title": "Smart Contract Security Researcher",
        "text": "OpenZeppelin is looking for a Smart Contract Security Researcher. Remote. You will analyze EVM bytecode, audit multi-million dollar decentralized finance protocols, and secure Web3 crypto wallet custody vaults. Qualifications: Proven competitive bug bounty track record. Package: 40-60 LPA plus research grants. Apply at https://openzeppelin.com/jobs.",
        "label": 0,
        "category": "LEGIT_CRYPTO",
        "contrast_pair_id": None,
        "notes": "Authentic Web3 security auditor",
    },
    {
        "id": 23,
        "name": "Legit Startup: Informal Lean Seed-Stage Job",
        "company": "HyperDope Labs",
        "title": "Early Backend Hacker",
        "text": "We are a seed-funded team of 4 ex-Google engineers building AI agents for supply chain. Looking for a cracked backend dev who loves Python, Rust, and shipping fast. No bureaucracy, 100% remote, zero useless meetings. Pay is 18-24 LPA with up to 1 percent equity. DM code samples or GitHub to founders@hyperdope.ai.",
        "label": 0,
        "category": "LEGIT_START",
        "contrast_pair_id": None,
        "notes": "Casual informal modern startup slang",
    },
    {
        "id": 24,
        "name": "Legit Enterprise: Standard No Application Fee Clause",
        "company": "Larsen & Toubro Heavy Engineering",
        "title": "Structural Design Engineer",
        "text": "L&T Heavy Engineering invites applications for Structural Design Engineers in Hazira. Key responsibilities: FEA modeling of pressure vessels and thermal stress analysis. B.E/B.Tech in Mechanical Engineering with 4-8 years experience. Note: L&T strictly does not charge any application or recruitment fee at any stage of the hiring process. Apply via https://www.larsentoubro.com/careers.",
        "label": 0,
        "category": "LEGIT_CORP",
        "contrast_pair_id": None,
        "notes": "Explicit 'no fee' disclaimer in authentic JD",
    },
    {
        "id": 25,
        "name": "Legit Urgent: Urgent Corporate Production Outage Role",
        "company": "CleverTap",
        "title": "Site Reliability Engineer - Urgent Need",
        "text": "Urgent requirement for Senior SRE in Mumbai. We need immediate joiners to manage our Kubernetes telemetry clusters handling 10 billion events per day. Candidates must have deep Linux troubleshooting, Terraform, and Prometheus experience. Notice period less than 15 days strongly preferred. CTC: 22-32 LPA. Apply at careers@clevertap.com.",
        "label": 0,
        "category": "LEGIT_CORP",
        "contrast_pair_id": None,
        "notes": "Urgent corporate operational necessity without scam pressure",
    },
    {
        "id": 26,
        "name": "Legit Internship: Zero-Experience Mechanical Intern",
        "company": "Tata Motors Fleet Division",
        "title": "Summer Mechanical Engineering Intern",
        "text": "Tata Motors is accepting applications for Summer Engineering Interns at our Pune automotive plant. Open to pre-final year B.Tech Mechanical students. No prior industry experience required. Stipend: 25000 per month with subsidized canteen and bus transport. Selection based on college academic percentage and technical interview round. Apply via campus placement cell.",
        "label": 0,
        "category": "LEGIT_CORP",
        "contrast_pair_id": None,
        "notes": "Legitimate no-experience internship with realistic stipend",
    },
    {
        "id": 27,
        "name": "Legit Customer Support: Night Shift Call Center",
        "company": "Teleperformance India",
        "title": "Customer Service Associate (US Process)",
        "text": "Teleperformance is hiring Customer Service Associates for our international US voice process in Gurugram. Handle inbound customer inquiries regarding telecom billing. Any graduate or undergraduate with fluent English. Night shifts with two-way air-conditioned cab facility. Salary: 28,000 to 35,000 per month plus monthly performance incentives. Walk-in interviews Monday to Friday.",
        "label": 0,
        "category": "LEGIT_BPO",
        "contrast_pair_id": None,
        "notes": "Standard BPO job description with realistic night shift salary",
    },
    {
        "id": 28,
        "name": "Legit Corporate Banking: Trade Finance Letter of Credit Specialist",
        "company": "Axis Bank",
        "title": "Trade Finance Operations Officer",
        "text": "Axis Bank is seeking a Trade Finance Operations Officer in Mumbai. Responsibilities include vetting international Letters of Credit, verifying export documentation, ensuring FEMA and RBI compliance, and releasing foreign bank wire payments. Minimum 3 years in bank trade operations. Competitive salary with banking benefits. Submit resume at axisbank.com/careers.",
        "label": 0,
        "category": "LEGIT_BANK",
        "contrast_pair_id": None,
        "notes": "Legitimate banking operations with foreign wire payments",
    },
    {
        "id": 29,
        "name": "Legit Remote: International US Company Hiring in India",
        "company": "Automattic",
        "title": "Code Wrangler (WordPress Core)",
        "text": "Automattic is the company behind WordPress.com and WooCommerce. We are hiring Code Wranglers globally, including India. Work from home with flexible schedules. Responsibilities: Maintain PHP/JavaScript codebases and contribute to open source. We offer open vacation, hardware setup allowance, and annual worldwide team meetups. Apply at automattic.com/work-with-us.",
        "label": 0,
        "category": "LEGIT_REMOTE",
        "contrast_pair_id": None,
        "notes": "Authentic distributed international company",
    },
    {
        "id": 30,
        "name": "Legit Healthcare: Clinical Research Coordinator",
        "company": "Syngene International",
        "title": "Clinical Research Coordinator",
        "text": "Syngene International is hiring a Clinical Research Coordinator in Hyderabad. Monitor clinical trial adherence to ICH-GCP protocols, maintain patient case report forms, and liaise with regulatory authorities. B.Pharm or M.Sc in Life Sciences with 1-3 years experience required. Salary commensurate with experience. Official careers portal: syngeneintl.com.",
        "label": 0,
        "category": "LEGIT_CORP",
        "contrast_pair_id": None,
        "notes": "Legitimate pharmaceutical clinical research post",
    },
    {
        "id": 31,
        "name": "Legit Sales: Business Development Executive with Target Commission",
        "company": "Justdial Limited",
        "title": "Field Sales Executive",
        "text": "Justdial is hiring Field Sales Executives across Delhi NCR. Meet local business owners, present digital marketing packages, and close merchant onboarding deals. Fixed salary: 22,000 per month plus uncapped weekly performance incentives based on sales targets. Two-wheeler and valid driving license mandatory. Walk-in with resume at our Noida regional office.",
        "label": 0,
        "category": "LEGIT_CORP",
        "contrast_pair_id": None,
        "notes": "Legitimate commission-based field sales role",
    },
    {
        "id": 32,
        "name": "Legit Creative: Motion Graphics Video Editor",
        "company": "Schbang Digital",
        "title": "Senior Motion Designer",
        "text": "Schbang is looking for a Senior Motion Designer in Mumbai. Create high-impact social media animations, commercial video reels, and brand identity videos using After Effects and Premiere Pro. Requirements: 3+ years agency experience and solid showreel. CTC: 7-10 LPA. Email your portfolio link and resume to design-careers@schbang.com.",
        "label": 0,
        "category": "LEGIT_CORP",
        "contrast_pair_id": None,
        "notes": "Legitimate agency creative design posting",
    },

    # ==================================================================
    # 3. DISGUISED SCAMS & INDIRECT SCAMS (12 Cases)
    # Scams that avoid obvious red-flag words, use formal tone,
    # or disguise extortion as onboarding/proctoring/wallet setup.
    # ==================================================================

    {
        "id": 33,
        "name": "Disguised Scam: Polished Corporate Trainee Security Deposit",
        "company": "OmniCorp Infrastructure Global",
        "title": "Executive Management Associate",
        "text": "OmniCorp Global announces its 2026 Young Leadership Cohort. Candidates undergo rotational placements across corporate strategy, operations, and fiscal governance. Package: 12 LPA. To guarantee candidate compliance with confidential corporate training IP, accepted candidates must initiate a refundable commitment disbursement of 4500 INR prior to issuance of joining credentials. Contact recruitment-desk@omnicorpglobal.net.",
        "label": 1,
        "category": "SCAM_DEPOSIT",
        "contrast_pair_id": None,
        "notes": "Disguised refundable commitment disbursement using executive language",
    },
    {
        "id": 34,
        "name": "Disguised Scam: Third-Party Proctoring Slot Fee",
        "company": "Stellaris Consulting Group",
        "title": "Business Intelligence Analyst",
        "text": "Stellaris Consulting is shortlisting Business Intelligence Analysts. Qualifications: Knowledge of PowerBI and relational SQL. Package: 8.5 LPA. To confirm your proctored assessment slot with our third-party testing vendor, an administrative evaluation charge of 850 rupees must be completed online within 4 hours. Transfer receipt to testing@stellarisconsulting.in.",
        "label": 1,
        "category": "SCAM_FEE",
        "contrast_pair_id": None,
        "notes": "Candidate instructed to pay administrative evaluation charge for test slot",
    },
    {
        "id": 35,
        "name": "Disguised Scam: Candidate Wallet Activation Task",
        "company": "Apex Digital Clearing",
        "title": "Transaction Validation Assistant",
        "text": "Work from home reviewing merchant e-commerce settlements. Monthly remuneration 38,000 INR. Prior to your initial assignment batch, you must activate your candidate settlement portal wallet by authorizing an initial security allocation of 1,950 INR. Your allocation will be returned with your first commission cycle. Reach coordinator on Telegram.",
        "label": 1,
        "category": "SCAM_TASK",
        "contrast_pair_id": None,
        "notes": "Candidate wallet activation fee for task scheme",
    },
    {
        "id": 36,
        "name": "Disguised Scam: IT Equipment Courier Transit Insurance",
        "company": "Vanguard Remote Services",
        "title": "Remote Medical Transcriptionist",
        "text": "Vanguard Remote Services provides full home transcription workstations including dual monitors and noise-cancelling headsets. Candidates are issued free hardware, but per logistics transit policy, the candidate must cover the 2,200 INR cargo transit insurance charge prior to shipment dispatch. Insurance is reimbursed on day 1. WhatsApp +91 9345678901.",
        "label": 1,
        "category": "SCAM_DEPOSIT",
        "contrast_pair_id": None,
        "notes": "Disguised equipment courier transit insurance charge",
    },
    {
        "id": 37,
        "name": "Disguised Scam: Corporate Uniform & ID Badge Clearance",
        "company": "IndoGulf Aviation Ground Handling",
        "title": "Airport Ground Staff Executive",
        "text": "Direct recruitment for Airport Ground Operations at terminal 3. Monthly salary: 32,000 INR. Selection based on telephonic interview. Candidates must purchase their official aviation security pass and high-visibility uniform package by depositing 3,250 INR to our logistics nodal account. WhatsApp HR at +91 9871234560.",
        "label": 1,
        "category": "SCAM_FEE",
        "contrast_pair_id": None,
        "notes": "Aviation uniform and airport security pass fee",
    },
    {
        "id": 38,
        "name": "Disguised Scam: Netbanking Pre-Authorization Phishing",
        "company": "Federal Trust Capital Partners",
        "title": "Junior Financial Associate",
        "text": "Your application for Junior Financial Associate has been approved. To establish direct credit link with our clearing house, please log into your personal internet banking portal and share the temporary verification authorization code received via SMS with our compliance officer at onboarding@federaltrust.org.",
        "label": 1,
        "category": "SCAM_CRED",
        "contrast_pair_id": None,
        "notes": "Credential phishing disguised as clearing house pre-authorization",
    },
    {
        "id": 39,
        "name": "Disguised Scam: Telegram Merchant Product Booster Scheme",
        "company": "Shopee Merchant Alliance",
        "title": "E-Commerce Review Specialist",
        "text": "Help global merchants optimize product ratings. Work 45 minutes daily on your smartphone. Earn 1,500 to 4,000 INR daily. All payouts disbursed instantly to your UPI handle. To receive your initial product evaluation allocation, connect with task supervisor on Telegram @MerchantAssoc2026.",
        "label": 1,
        "category": "SCAM_TASK",
        "contrast_pair_id": None,
        "notes": "Merchant rating task scam via Telegram",
    },
    {
        "id": 40,
        "name": "Disguised Scam: Corporate Laptop Buyback Advance Check Scam",
        "company": "Apex Global Solutions LLC",
        "title": "Executive Virtual Assistant",
        "text": "We are excited to bring you onto our executive support team. Our corporate finance department will mail you an electronic advance reimbursement draft of 4,200 USD. Deposit the draft into your checking account and wire the vendor balance to our certified Apple hardware enterprise supplier. Email bank slip to finance@apexsolutions-portal.com.",
        "label": 1,
        "category": "SCAM_CHECK",
        "contrast_pair_id": None,
        "notes": "Check fraud using polished corporate assistant phrasing",
    },
    {
        "id": 41,
        "name": "Disguised Scam: WhatsApp Aadhaar/PAN Loan Collateral Extortion",
        "company": "QuickFin Loans & Staffing",
        "title": "Backend Document Reviewer",
        "text": "Work from home verifying consumer loan files. Earn 25,000 per month. Before scheduling orientation, send high-resolution front and back photos of your original Aadhaar card, PAN card, and a short video selfie holding your ID to WhatsApp +91 9123098765 to initiate gate pass clearance.",
        "label": 1,
        "category": "SCAM_DOCS",
        "contrast_pair_id": None,
        "notes": "Premature WhatsApp identity extortion",
    },
    {
        "id": 42,
        "name": "Disguised Scam: Crypto Yield Arbitrage Internship",
        "company": "QuantEdge Blockchain Ventures",
        "title": "Cryptocurrency Arbitrage Trainee",
        "text": "QuantEdge is seeking digital trading interns. Learn automated market making and earn 300 to 800 USDT weekly. Trainees must connect an active decentralized wallet and provide 100 USDT liquidity commitment to the testing smart contract to access proprietary arbitrage algorithms. Telegram contact @QuantEdgeTrainee.",
        "label": 1,
        "category": "SCAM_CRYPTO",
        "contrast_pair_id": None,
        "notes": "Crypto task scheme disguised as quantitative trading internship",
    },
    {
        "id": 43,
        "name": "Disguised Scam: Direct Selection Gate Pass Fee",
        "company": "Metro Rail Infrastructure Services",
        "title": "Ticket Counter Executive",
        "text": "Direct recruitment for Metro Station Ticket Counter Executives. Monthly pay 26,500 INR. Instant selection based on matriculation marks. Candidates must transfer 1,750 INR gate pass and medical examination registration charge via UPI to confirm venue reporting slot. Contact on WhatsApp +91 9988112233.",
        "label": 1,
        "category": "SCAM_FEE",
        "contrast_pair_id": None,
        "notes": "Direct selection without interview + gate pass fee",
    },
    {
        "id": 44,
        "name": "Disguised Scam: Predatory Urgency 2-Hour Window",
        "company": "BlueChip Career Connect",
        "title": "Operations Associate",
        "text": "FINAL INTIMATION: Your interview dossier for BlueChip Operations has been approved by the board. To lock your appointment letter and employee code, complete the mandatory documentation token of 1,600 INR within the next 2 hours or your seat will be automatically forfeited to the waitlist. Send screenshot to hr-verify@bluechip-desk.net.",
        "label": 1,
        "category": "SCAM_URGENT",
        "contrast_pair_id": None,
        "notes": "Predatory 2-hour countdown payment coercion",
    },

    # ==================================================================
    # 4. LINGUISTIC VARIATIONS, HINGLISH & INFORMAL STYLES (20 Cases)
    # 10 Legitimate + 10 Scam with varied phrasing, Indian English,
    # typos, Hinglish, concise or verbose structures.
    # ==================================================================

    # Hinglish & Indian English Legitimate
    {
        "id": 45,
        "name": "Hinglish Legit: Small Software Agency Opening",
        "company": "CodeCrafters Surat",
        "title": "Junior Web Developer",
        "text": "Surat based IT agency hiring Junior PHP Laravel developer. Candidate ko basic HTML, CSS aur MySQL aana chahiye. Office timing 10 AM to 7 PM. Salary 15,000 to 22,000 per month based on technical skill. Direct technical interview hoga office me. Send resume to jobs@codecrafters.in.",
        "label": 0,
        "category": "LEGIT_START",
        "contrast_pair_id": None,
        "notes": "Authentic small Indian agency in conversational English/Hinglish",
    },
    {
        "id": 46,
        "name": "Indian English Legit: Accounts Assistant Urgent Joiner",
        "company": "Shree Balaji Traders",
        "title": "Tally Accounts Assistant",
        "text": "Urgent requirement for Tally Accounts Assistant in Ahmedabad wholesale market. Candidate must have practical knowledge of GST return, e-way bill generation, and bank reconciliation. B.Com passout with 1-2 years experience preferred. Salary 18000 to 24000 pm. Direct walk-in interview with CV.",
        "label": 0,
        "category": "LEGIT_CORP",
        "contrast_pair_id": None,
        "notes": "Authentic Indian SME accounting job with bank reconciliation",
    },
    {
        "id": 47,
        "name": "Very Brief Legit: Python Microservice Dev",
        "company": "Kinetix Tech",
        "title": "Python Developer",
        "text": "Hiring Python backend developer. 3 years experience with FastAPI, Redis, and PostgreSQL. Remote OK. Salary 14-18 LPA. Email resume to careers@kinetix.tech.",
        "label": 0,
        "category": "LEGIT_START",
        "contrast_pair_id": None,
        "notes": "Extremely brief legitimate tech posting (3 lines)",
    },
    {
        "id": 48,
        "name": "Typo / Informal Legit: React Native Dev",
        "company": "Appify Labs",
        "title": "Mobile App Developer",
        "text": "heyy we need react native dev urgently for our food delivery client app. must have 2 yr exp in redux and android/ios publishing. gud pay around 10-15 lpa. work from home. send portfolio links at hire@appifylabs.io.",
        "label": 0,
        "category": "LEGIT_START",
        "contrast_pair_id": None,
        "notes": "Informal lowercase slang with typos in legitimate posting",
    },
    {
        "id": 49,
        "name": "Verbose Legit: Enterprise Cloud Governance Lead",
        "company": "Hexaware Technologies",
        "title": "Principal Enterprise Architect - Cloud Platforms",
        "text": "Hexaware Technologies is looking for a Principal Enterprise Architect to lead strategic cloud enablement frameworks. The architect will design multi-cloud FinOps models, enforce zero-trust identity architectures across AWS and Azure environments, evaluate vendor API security boundaries, and chair the technical architecture governance review board. Qualifications: Bachelor or Master of Technology, 14+ years in enterprise IT, TOGAF certification preferred. CTC: 42-55 LPA with annual performance equity bonuses and executive healthcare. Structured 4-stage evaluation: Preliminary HR screening, architectural case presentation, executive panel discussion, and compensation committee review. Apply at https://hexaware.com/careers.",
        "label": 0,
        "category": "LEGIT_CORP",
        "contrast_pair_id": None,
        "notes": "Verbose 400-word enterprise corporate JD",
    },
    {
        "id": 50,
        "name": "Indian English Legit: Delivery Fleet Supervisor",
        "company": "Shadowfax Logistics",
        "title": "Hub Delivery Supervisor",
        "text": "Shadowfax is hiring Hub Delivery Supervisors in Jaipur. Supervise 40+ delivery executives, monitor timely order pickups, and manage local hub inventory. Fixed salary 22,000 plus petrol allowance and performance incentives. Candidate must have own two-wheeler and Android smartphone. Contact hr.north@shadowfax.in.",
        "label": 0,
        "category": "LEGIT_BPO",
        "contrast_pair_id": None,
        "notes": "Standard Indian logistics hub role",
    },
    {
        "id": 51,
        "name": "Legit Foreign Startup: German SaaS Remote in India",
        "company": "Staffbase GmbH",
        "title": "Senior Go Infrastructure Engineer",
        "text": "Staffbase is a German enterprise internal communications platform. We are hiring a Senior Go Engineer based in India (remote contractor). You will optimize our microservices architecture, reduce latency across global Kubernetes clusters, and mentor junior engineers. Compensation: 45,000 to 60,000 EUR per annum. Apply at staffbase.com/careers.",
        "label": 0,
        "category": "LEGIT_REMOTE",
        "contrast_pair_id": None,
        "notes": "Legitimate foreign company hiring Indian remote contractor",
    },
    {
        "id": 52,
        "name": "Legit High Salary: Staff Machine Learning Scientist",
        "company": "Krutrim AI",
        "title": "Staff ML Scientist - LLM Pretraining",
        "text": "Krutrim is hiring Staff ML Scientists in Bengaluru. You will train multi-billion parameter multilingual foundation models, optimize GPU distributed training clusters, and publish research papers. PhD or MS in CS with 5+ years deep learning research experience required. Compensation: 50-80 LPA plus significant equity. Apply at careers@krutrim.ai.",
        "label": 0,
        "category": "LEGIT_SENIOR",
        "contrast_pair_id": None,
        "notes": "High compensation for frontier AI research",
    },
    {
        "id": 53,
        "name": "Legit University Job: Assistant Professor CS",
        "company": "Shiv Nadar University",
        "title": "Assistant Professor - Computer Science",
        "text": "Shiv Nadar University invites applications for faculty positions in the Department of Computer Science. Candidates must have a PhD in Computer Science from a reputable institution with demonstrated research publications in peer-reviewed conferences. UGC scale compensation with on-campus housing and research seed grant. Apply with CV, research statement, and teaching philosophy to faculty.recruitment@snu.edu.in.",
        "label": 0,
        "category": "LEGIT_CORP",
        "contrast_pair_id": None,
        "notes": "Legitimate university academic appointment",
    },
    {
        "id": 54,
        "name": "Legit Legal / Compliance: Corporate Legal Counsel",
        "company": "Piramal Enterprises",
        "title": "Legal Counsel - Contracts & M&A",
        "text": "Piramal Enterprises is hiring a Legal Counsel in Mumbai. Review cross-border commercial contracts, assist in M&A due diligence, and advise on corporate governance. LL.B from a premier law school with 4-7 years corporate legal experience required. Salary: 18-26 LPA. Apply at piramal.com/careers.",
        "label": 0,
        "category": "LEGIT_CORP",
        "contrast_pair_id": None,
        "notes": "Legitimate corporate legal role",
    },

    # Hinglish & Indian English Scams
    {
        "id": 55,
        "name": "Hinglish Scam: Typing Job Form Registration",
        "company": "FastEarn Digital Hub",
        "title": "Online Typing Executive",
        "text": "Ghar baithe typing karke daily 2000 se 4000 kamao. Koi interview nahi hoga. Mobile se kaam karna hai. Kaam shuru karne ke liye software registration charge 999 rupaye UPI se pay karna padega. Payment screenshot WhatsApp number 9876543210 pe bhejo turant.",
        "label": 1,
        "category": "SCAM_FEE",
        "contrast_pair_id": None,
        "notes": "Hinglish data entry scam asking for 999 UPI fee",
    },
    {
        "id": 56,
        "name": "Hinglish Scam: Direct Bank Job Gate Pass",
        "company": "HDFC Banking Recruitment Cell",
        "title": "Bank Branch Assistant",
        "text": "Private bank me direct joining for Back Office Clerk. Monthly salary 32000. Selection confirm ho gaya hai. Gate pass aur training uniform ke liye 1500 rupaye send karo via Google Pay. Paise bhejte hi offer letter WhatsApp par mil jayega.",
        "label": 1,
        "category": "SCAM_FEE",
        "contrast_pair_id": None,
        "notes": "Hinglish bank impersonation scam demanding uniform fee",
    },
    {
        "id": 57,
        "name": "Indian English Scam: Railway Parcel Sorter Fake Job",
        "company": "Indian Railway Cargo Parcel Service",
        "title": "Station Parcel Supervisor",
        "text": "Direct recruitment for Railway Parcel Sorting Staff. 10th/12th pass eligible. Monthly pay 28500. No CBT exam. Candidates must submit 2150 INR medical fitness verification charge to our official zonal recruitment agent via UPI. WhatsApp +91 9911223344.",
        "label": 1,
        "category": "SCAM_FEE",
        "contrast_pair_id": None,
        "notes": "Government/Railway impersonation scam asking for medical verification charge",
    },
    {
        "id": 58,
        "name": "Informal / Slang Scam: Daily Cash Crypto Like Work",
        "company": "CryptoTask King",
        "title": "Crypto Promoter",
        "text": "bro ez cash daily 5k just like posts on insta and review places on maps. instant payment to upi. recharge 500 first to get vip tasks. message telegram @ezcashboss now limited seats bro.",
        "label": 1,
        "category": "SCAM_TASK",
        "contrast_pair_id": None,
        "notes": "Slang-filled task scam asking for 500 recharge",
    },
    {
        "id": 59,
        "name": "Indirect Scam: Candidate File Processing Charge",
        "company": "Global Visa & Placement Desk",
        "title": "Overseas Logistics Clerk",
        "text": "Urgent opening for Canada / Gulf warehouse logistics clerks. Direct company visa provided. Salary 1.2 Lakhs per month. To forward your application dossier to immigration authorities, pay an initial file administrative fee of 3,500 rupees. Call +91 9812345670.",
        "label": 1,
        "category": "SCAM_FEE",
        "contrast_pair_id": None,
        "notes": "Overseas visa dossier processing fee scam",
    },
    {
        "id": 60,
        "name": "Indirect Scam: Laptop Shipping Courier Insurance",
        "company": "TechPro Remote Staffing",
        "title": "Remote Data Clerk",
        "text": "You are selected for remote data entry. A company laptop has been packaged for your address. Please transfer 1,850 INR courier transit insurance via PhonePe to release tracking number. The amount will be refunded with your first week payout.",
        "label": 1,
        "category": "SCAM_DEPOSIT",
        "contrast_pair_id": None,
        "notes": "Courier insurance transit fee scam",
    },
    {
        "id": 61,
        "name": "Indirect Scam: Account Authorization OTP Request",
        "company": "Prime HR Payroll Services",
        "title": "Document Assistant",
        "text": "Dear applicant, to confirm your salary bank account registration, our automated bank server has sent an authorization OTP code to your mobile. Please reply with the 6 digit code immediately to ensure salary auto-credit activation.",
        "label": 1,
        "category": "SCAM_CRED",
        "contrast_pair_id": None,
        "notes": "OTP harvesting scam for salary account verification",
    },
    {
        "id": 62,
        "name": "Indirect Scam: WhatsApp Document Submission Prior to Test",
        "company": "AirTech Ground Handling",
        "title": "Cabin Crew Assistant",
        "text": "Hiring Cabin Crew Assistants. Salary 40,000 per month. Candidate must send clear copies of passport, Aadhaar, PAN card, and 6 months bank account statement to WhatsApp +91 9712345678 to receive hall ticket for interview.",
        "label": 1,
        "category": "SCAM_DOCS",
        "contrast_pair_id": None,
        "notes": "Identity document extortion prior to hall ticket issuance",
    },
    {
        "id": 63,
        "name": "Indirect Scam: Diluted Corporate Trainee Fee",
        "company": "Zenith Global Consulting",
        "title": "Junior Business Analyst",
        "text": "Zenith Global is hiring Junior Business Analysts. We consult for multinational enterprises across finance and retail. Selected candidates undergo intensive 3-month corporate training on Tableau, SQL, and agile project delivery. Compensation: 7 LPA. To confirm candidate commitment and reserve seat with our third-party corporate training partner, a refundable candidate registration amount of 1,450 INR must be remitted prior to orientation. Email proof to hr@zenithglobal-careers.net.",
        "label": 1,
        "category": "SCAM_DEPOSIT",
        "contrast_pair_id": None,
        "notes": "Professional consulting trainee posting with refundable registration fee",
    },
    {
        "id": 64,
        "name": "Indirect Scam: Task Unlocking Commission",
        "company": "Digital Media Growth Partners",
        "title": "Online Content Rater",
        "text": "Review YouTube videos and rate hotel websites. Work flexible hours from your smartphone. Earn 2,000 to 5,000 per day. To unlock your daily tier-2 high-commission task batch, candidate must initiate a temporary security transfer of 1,200 INR via UPI to our settlement merchant. Connect on Telegram @TaskUnlock2026.",
        "label": 1,
        "category": "SCAM_TASK",
        "contrast_pair_id": None,
        "notes": "Task unlocking security transfer scam",
    },
]
